Update shared-test.yml

diff --git a/.github/workflows/shared-test.yml b/.github/workflows/shared-test.yml
--- a/.github/workflows/shared-test.yml
+++ b/.github/workflows/shared-test.yml
@@ -42,24 +42,27 @@ jobs:
           # Find test projects matching *.Tests.csproj
           find . -name "*.Tests.csproj" | while read -r testProject; do
             echo "Running tests for $testProject"
-            resultsDir="TestResults-${{ inputs.project-name }}/$(basename "$testProject" .csproj)"
+            resultsDir="TestResults-AspireStarterApp/$(basename "$testProject" .csproj)"
             coverageDir="$resultsDir/CoverageResults"
             mkdir -p "$resultsDir"
             mkdir -p "$coverageDir"
 
-            # Execute dotnet test and capture exit code
-            dotnet test "$testProject" --logger trx --results-directory "$resultsDir" --no-restore --no-build --collect:"XPlat Code Coverage" \
-              /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura,opencover,json" /p:CoverletOutput="$coverageDir/coverage" 
-            test_result=$?
-
-            # Check for test execution errors
-            if [ $test_result -ne 0 ]; then
-              echo "Tests for $testProject failed."
-              # Optionally log detailed test output to a file
-              echo "Test output for $testProject:" >> test-output.log
-              dotnet test "$testProject" >> test-output.log 2>&1
-              exit 1  # Exit the workflow if any test fails
-            fi 
+            # Execute dotnet test for each format and capture exit code
+            for format in cobertura opencover json; do
+              dotnet test "$testProject" --logger trx --results-directory "$resultsDir" --no-restore --no-build --collect:"XPlat Code Coverage" \
+                /p:CollectCoverage=true \
+                /p:CoverletOutput="$coverageDir/coverage.$format" \
+                /p:CoverletOutputFormat=$format
+              test_result=$?
+              
+              if [ $test_result -ne 0 ]; then
+                echo "Tests for $testProject failed in $format format."
+                # Optionally log detailed test output to a file
+                echo "Test output for $testProject ($format):" >> test-output.log
+                dotnet test "$testProject" >> test-output.log 2>&1
+                exit 1  # Exit the workflow if any test fails
+              fi
+            done
           done
 
       - name: Upload the test results
